services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=digitdb
      - DB_USER=digituser
      - DB_PASSWORD=digitpass

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: digitdb
      POSTGRES_USER: digituser
      POSTGRES_PASSWORD: digitpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
